name = "Luxana"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0087a5961ef73095a55988f5e13551d4fc3f52fc42d9640698ed810df87a2da6"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
