name = "Basepack Forge"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b7ebfd77a88fdc60e1212be70b179d730f835520d783df320f7fdf71932869b"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
