name = "Basepack Forge"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47634011ed292c0ba1a533dbea3406bba5e7f8824c3ecfeffaf9a64afb2da9ac"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
