name = "Luxana"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f4c60ac0c372e135648e70bbf269c13f5e9c326a81922212a256de35b9bb6a8"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
