name = "Basepack Forge"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0b5a652e25feb2b25a4b5372208139b6df86f5200b4713137cac9e10fe57ba1"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
