name = "Luxana"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8840fcd9cfa887345ed512e3e2b04959e18e8715f5cfd0c3694e25d2de0b22e"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
