name = "Luxana"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc3d6de04eaa2a887c1d3ce98f067e18f8fdaaa5f2b92a26dc810e6fa6edb103"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
