name = "Basepack Forge"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04d660157df7672c99664a3f5db738c8760090289fb2ca3d0e5c48ded790412c"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
