name = "Luxana"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03c75c6b9e62aa278c1e1a57d3f15a47fa0c33003cb05d76b8483547eaae93b9"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
