name = "Luxana"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3feff131cdd054d68943fb3457641e2fcfb2d86ef15f5577757c40d75ad81af"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
