name = "Basepack Forge"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42c7c177a90420ac508c6b2e243bf3221ec3b18a87c2b914f3675caeb0284879"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
