name = "Basepack Forge"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbec8cbbbfdbc1e042ea17aa1a35c36c117e9c013d45a3c91a9893ae50160253"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
