name = "Luxana"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df1ad8ca77a58e14f76e54b3e3d4bf85758c1787da631f7367d5f84c9d4d4e66"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
