name = "Luxana"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3767443f5b29180ce2286a8c46f51cadde7eec6da04361e378c3e5de5b0f53f6"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
