name = "Basepack Forge"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e795abc6c98b50c88c37aa1f8034ba26cba7bced46b1f7be7159a74b2fbca152"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
