name = "Basepack Forge"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d38a398450638a3f3bcf1a7f515af43b5123652e18cb4f339193c45cdf18e68"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
