name = "Luxana"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d84e75b9714e3af42e940b4a8f5ada633001a07abfed065f6d834b95264728f6"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
