name = "Luxana"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aea2604ce3a30919067475a2c7d46a2b2d8ae018524f857e32060113a6a1b694"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
