name = "Luxana"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42487c2d8783d2eb2ad402874a1994c0cbdf97b242ec505819f713f56da7a79a"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
